version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:10000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 10000:10000
    env_file:                       
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
